name: Unity

on: [pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      projectName: "StickmanSliding"
      projectPath: "./StickmanSliding.Unity/"
  deploy:
    name: Deploy
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      projectName: "StickmanSliding"
    permissions:
      pages: write
      id-token: write